# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openfarms.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('openfarms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDatasource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openfarms.Datasource')),
                ('csv_file', models.FileField(upload_to='csv-files/', validators=['csv_validator'])),
            ],
            bases=('openfarms.datasource',),
        ),
    ]
